// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var PrecisUtils$BsPrecis = require("./PrecisUtils.bs.js");
var PrecisMapping$BsPrecis = require("./PrecisMapping.bs.js");

var j = "    justin";

console.log(PrecisMapping$BsPrecis.stripSpaces(PrecisUtils$BsPrecis.toCodePointList(j)));

exports.j = j;
/*  Not a pure module */
