// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Caml_splice_call = require("bs-platform/lib/js/caml_splice_call.js");

var PrecisError = Caml_exceptions.create("PrecisUtils-BsPrecis.PrecisError");

function toCodePointList(s) {
  var s$1 = s;
  var _i = 0;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var i = _i;
    var match = s$1.codePointAt(i);
    if (match !== undefined) {
      _acc = Pervasives.$at(acc, /* :: */[
            match,
            /* [] */0
          ]);
      _i = i + 1 | 0;
      continue ;
    } else {
      return acc;
    }
  };
}

function fromCodePointList(codePointList) {
  return Caml_splice_call.spliceApply(String.fromCodePoint, [ArrayLabels.of_list(codePointList)]);
}

exports.PrecisError = PrecisError;
exports.toCodePointList = toCodePointList;
exports.fromCodePointList = fromCodePointList;
/* No side effect */
