// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function getDirectionProperty(x) {
  if (x >= 1 && x <= 8 || x >= 14 && x <= 27) {
    return /* BN */0;
  } else if (x >= 28 && x <= 30) {
    return /* B */12;
  } else if (x >= 33 && x <= 34) {
    return /* ON */3;
  } else if (x >= 35 && x <= 37) {
    return /* ET */11;
  } else if (x >= 38 && x <= 42) {
    return /* ON */3;
  } else if (x >= 46 && x <= 47) {
    return /* CS */8;
  } else if (x >= 48 && x <= 57) {
    return /* EN */9;
  } else if (x >= 59 && x <= 64) {
    return /* ON */3;
  } else if (x >= 65 && x <= 90) {
    return /* L */10;
  } else if (x >= 91 && x <= 96) {
    return /* ON */3;
  } else if (x >= 97 && x <= 122) {
    return /* L */10;
  } else if (x >= 123 && x <= 126) {
    return /* ON */3;
  } else if (x >= 127 && x <= 132 || x >= 134 && x <= 159) {
    return /* BN */0;
  } else if (x >= 162 && x <= 165) {
    return /* ET */11;
  } else if (x >= 166 && x <= 169 || x >= 171 && x <= 172 || x >= 174 && x <= 175) {
    return /* ON */3;
  } else if (x >= 176 && x <= 177) {
    return /* ET */11;
  } else if (x >= 178 && x <= 179) {
    return /* EN */9;
  } else if (x >= 182 && x <= 184 || x >= 187 && x <= 191) {
    return /* ON */3;
  } else if (x >= 192 && x <= 214 || x >= 216 && x <= 246 || x >= 248 && x <= 696) {
    return /* L */10;
  } else if (x >= 697 && x <= 698) {
    return /* ON */3;
  } else if (x >= 699 && x <= 705) {
    return /* L */10;
  } else if (x >= 706 && x <= 719) {
    return /* ON */3;
  } else if (x >= 720 && x <= 721) {
    return /* L */10;
  } else if (x >= 722 && x <= 735) {
    return /* ON */3;
  } else if (x >= 736 && x <= 740) {
    return /* L */10;
  } else if (x >= 741 && x <= 749 || x >= 751 && x <= 767) {
    return /* ON */3;
  } else if (x >= 768 && x <= 879) {
    return /* NSM */6;
  } else if (x >= 880 && x <= 883) {
    return /* L */10;
  } else if (x >= 884 && x <= 885) {
    return /* ON */3;
  } else if (x >= 886 && x <= 893 || x >= 895 && x <= 899) {
    return /* L */10;
  } else if (x >= 900 && x <= 901) {
    return /* ON */3;
  } else if (x >= 904 && x <= 1013 || x >= 1015 && x <= 1154) {
    return /* L */10;
  } else if (x >= 1155 && x <= 1161) {
    return /* NSM */6;
  } else if (x >= 1162 && x <= 1417) {
    return /* L */10;
  } else if (x >= 1418 && x <= 1422) {
    return /* ON */3;
  } else if (x >= 1423 && x <= 1424) {
    return /* ET */11;
  } else if (x >= 1425 && x <= 1469 || x >= 1473 && x <= 1474 || x >= 1476 && x <= 1477 || x >= 1479 && x <= 1487) {
    return /* NSM */6;
  } else if (x >= 1488 && x <= 1535) {
    return /* R */4;
  } else if (x >= 1536 && x <= 1541) {
    return /* AN */1;
  } else if (x >= 1542 && x <= 1543) {
    return /* ON */3;
  } else if (x >= 1545 && x <= 1546) {
    return /* ET */11;
  } else if (x >= 1550 && x <= 1551) {
    return /* ON */3;
  } else if (x >= 1552 && x <= 1562) {
    return /* NSM */6;
  } else if (x >= 1563 && x <= 1610) {
    return /* AL */5;
  } else if (x >= 1611 && x <= 1631) {
    return /* NSM */6;
  } else if (x >= 1632 && x <= 1641 || x >= 1643 && x <= 1644) {
    return /* AN */1;
  } else if (x >= 1645 && x <= 1647 || x >= 1649 && x <= 1749) {
    return /* AL */5;
  } else if (x >= 1750 && x <= 1756 || x >= 1759 && x <= 1764) {
    return /* NSM */6;
  } else if (x >= 1765 && x <= 1766) {
    return /* AL */5;
  } else if (x >= 1767 && x <= 1768 || x >= 1770 && x <= 1773) {
    return /* NSM */6;
  } else if (x >= 1774 && x <= 1775) {
    return /* AL */5;
  } else if (x >= 1776 && x <= 1785) {
    return /* EN */9;
  } else if (x >= 1786 && x <= 1808 || x >= 1810 && x <= 1839) {
    return /* AL */5;
  } else if (x >= 1840 && x <= 1868) {
    return /* NSM */6;
  } else if (x >= 1869 && x <= 1957) {
    return /* AL */5;
  } else if (x >= 1958 && x <= 1968) {
    return /* NSM */6;
  } else if (x >= 1969 && x <= 1983) {
    return /* AL */5;
  } else if (x >= 1984 && x <= 2026) {
    return /* R */4;
  } else if (x >= 2027 && x <= 2035) {
    return /* NSM */6;
  } else if (x >= 2036 && x <= 2037) {
    return /* R */4;
  } else if (x >= 2038 && x <= 2041) {
    return /* ON */3;
  } else if (x >= 2042 && x <= 2044 || x >= 2046 && x <= 2069) {
    return /* R */4;
  } else if (x >= 2070 && x <= 2073 || x >= 2075 && x <= 2083 || x >= 2085 && x <= 2087 || x >= 2089 && x <= 2095) {
    return /* NSM */6;
  } else if (x >= 2096 && x <= 2136) {
    return /* R */4;
  } else if (x >= 2137 && x <= 2141) {
    return /* NSM */6;
  } else if (x >= 2142 && x <= 2143) {
    return /* R */4;
  } else if (x >= 2144 && x <= 2258) {
    return /* AL */5;
  } else if (x >= 2259 && x <= 2273 || x >= 2275 && x <= 2306) {
    return /* NSM */6;
  } else if (x >= 2307 && x <= 2361 || x >= 2365 && x <= 2368) {
    return /* L */10;
  } else if (x >= 2369 && x <= 2376) {
    return /* NSM */6;
  } else if (x >= 2377 && x <= 2380 || x >= 2382 && x <= 2384) {
    return /* L */10;
  } else if (x >= 2385 && x <= 2391) {
    return /* NSM */6;
  } else if (x >= 2392 && x <= 2401) {
    return /* L */10;
  } else if (x >= 2402 && x <= 2403) {
    return /* NSM */6;
  } else if (x >= 2404 && x <= 2432 || x >= 2434 && x <= 2491 || x >= 2493 && x <= 2496) {
    return /* L */10;
  } else if (x >= 2497 && x <= 2502) {
    return /* NSM */6;
  } else if (x >= 2503 && x <= 2508 || x >= 2510 && x <= 2529) {
    return /* L */10;
  } else if (x >= 2530 && x <= 2533) {
    return /* NSM */6;
  } else if (x >= 2534 && x <= 2545) {
    return /* L */10;
  } else if (x >= 2546 && x <= 2547) {
    return /* ET */11;
  } else if (x >= 2548 && x <= 2554 || x >= 2556 && x <= 2557) {
    return /* L */10;
  } else if (x >= 2558 && x <= 2562) {
    return /* NSM */6;
  } else if (x >= 2563 && x <= 2619) {
    return /* L */10;
  } else if (x >= 2620 && x <= 2621) {
    return /* NSM */6;
  } else if (x >= 2622 && x <= 2624) {
    return /* L */10;
  } else if (x >= 2625 && x <= 2648) {
    return /* NSM */6;
  } else if (x >= 2649 && x <= 2671) {
    return /* L */10;
  } else if (x >= 2672 && x <= 2673) {
    return /* NSM */6;
  } else if (x >= 2674 && x <= 2676 || x >= 2678 && x <= 2688) {
    return /* L */10;
  } else if (x >= 2689 && x <= 2690) {
    return /* NSM */6;
  } else if (x >= 2691 && x <= 2747 || x >= 2749 && x <= 2752) {
    return /* L */10;
  } else if (x >= 2753 && x <= 2760) {
    return /* NSM */6;
  } else if (x >= 2761 && x <= 2764) {
    return /* L */10;
  } else if (x >= 2765 && x <= 2767) {
    return /* NSM */6;
  } else if (x >= 2768 && x <= 2785) {
    return /* L */10;
  } else if (x >= 2786 && x <= 2789) {
    return /* NSM */6;
  } else if (x >= 2790 && x <= 2800) {
    return /* L */10;
  } else if (x >= 2801 && x <= 2808) {
    return /* ET */11;
  } else if (x >= 2810 && x <= 2817) {
    return /* NSM */6;
  } else if (x >= 2818 && x <= 2875 || x >= 2877 && x <= 2878) {
    return /* L */10;
  } else if (x >= 2881 && x <= 2886) {
    return /* NSM */6;
  } else if (x >= 2887 && x <= 2892) {
    return /* L */10;
  } else if (x >= 2893 && x <= 2902) {
    return /* NSM */6;
  } else if (x >= 2903 && x <= 2913) {
    return /* L */10;
  } else if (x >= 2914 && x <= 2917) {
    return /* NSM */6;
  } else if (x >= 2918 && x <= 2945 || x >= 2947 && x <= 3007 || x >= 3009 && x <= 3020) {
    return /* L */10;
  } else if (x >= 3021 && x <= 3023) {
    return /* NSM */6;
  } else if (x >= 3024 && x <= 3058) {
    return /* L */10;
  } else if (x >= 3059 && x <= 3064 || x >= 3066 && x <= 3071) {
    return /* ON */3;
  } else if (x >= 3073 && x <= 3075 || x >= 3077 && x <= 3133) {
    return /* L */10;
  } else if (x >= 3134 && x <= 3136) {
    return /* NSM */6;
  } else if (x >= 3137 && x <= 3141) {
    return /* L */10;
  } else if (x >= 3142 && x <= 3159) {
    return /* NSM */6;
  } else if (x >= 3160 && x <= 3169) {
    return /* L */10;
  } else if (x >= 3170 && x <= 3173) {
    return /* NSM */6;
  } else if (x >= 3174 && x <= 3191) {
    return /* L */10;
  } else if (x >= 3192 && x <= 3198) {
    return /* ON */3;
  } else if (x >= 3199 && x <= 3200 || x >= 3202 && x <= 3259 || x >= 3261 && x <= 3275) {
    return /* L */10;
  } else if (x >= 3276 && x <= 3284) {
    return /* NSM */6;
  } else if (x >= 3285 && x <= 3297) {
    return /* L */10;
  } else if (x >= 3298 && x <= 3301) {
    return /* NSM */6;
  } else if (x >= 3302 && x <= 3327) {
    return /* L */10;
  } else if (x >= 3328 && x <= 3329) {
    return /* NSM */6;
  } else if (x >= 3330 && x <= 3386) {
    return /* L */10;
  } else if (x >= 3387 && x <= 3388) {
    return /* NSM */6;
  } else if (x >= 3389 && x <= 3392) {
    return /* L */10;
  } else if (x >= 3393 && x <= 3397) {
    return /* NSM */6;
  } else if (x >= 3398 && x <= 3404 || x >= 3406 && x <= 3425) {
    return /* L */10;
  } else if (x >= 3426 && x <= 3429) {
    return /* NSM */6;
  } else if (x >= 3430 && x <= 3529) {
    return /* L */10;
  } else if (x >= 3530 && x <= 3534) {
    return /* NSM */6;
  } else if (x >= 3535 && x <= 3537) {
    return /* L */10;
  } else if (x >= 3538 && x <= 3543) {
    return /* NSM */6;
  } else if (x >= 3544 && x <= 3632 || x >= 3634 && x <= 3635) {
    return /* L */10;
  } else if (x >= 3636 && x <= 3646) {
    return /* NSM */6;
  } else if (x >= 3648 && x <= 3654) {
    return /* L */10;
  } else if (x >= 3655 && x <= 3662) {
    return /* NSM */6;
  } else if (x >= 3663 && x <= 3760 || x >= 3762 && x <= 3763) {
    return /* L */10;
  } else if (x >= 3764 && x <= 3772) {
    return /* NSM */6;
  } else if (x >= 3773 && x <= 3783) {
    return /* L */10;
  } else if (x >= 3784 && x <= 3791) {
    return /* NSM */6;
  } else if (x >= 3792 && x <= 3863) {
    return /* L */10;
  } else if (x >= 3864 && x <= 3865) {
    return /* NSM */6;
  } else if (x >= 3866 && x <= 3892) {
    return /* L */10;
  } else if (x >= 3898 && x <= 3901) {
    return /* ON */3;
  } else if (x >= 3902 && x <= 3952) {
    return /* L */10;
  } else if (x >= 3953 && x <= 3966 || x >= 3968 && x <= 3972 || x >= 3974 && x <= 3975) {
    return /* NSM */6;
  } else if (x >= 3976 && x <= 3980) {
    return /* L */10;
  } else if (x >= 3981 && x <= 4029) {
    return /* NSM */6;
  } else if (x >= 4030 && x <= 4037 || x >= 4039 && x <= 4140) {
    return /* L */10;
  } else if (x >= 4141 && x <= 4144 || x >= 4146 && x <= 4151 || x >= 4153 && x <= 4154) {
    return /* NSM */6;
  } else if (x >= 4155 && x <= 4156) {
    return /* L */10;
  } else if (x >= 4157 && x <= 4158) {
    return /* NSM */6;
  } else if (x >= 4159 && x <= 4183) {
    return /* L */10;
  } else if (x >= 4184 && x <= 4185) {
    return /* NSM */6;
  } else if (x >= 4186 && x <= 4189) {
    return /* L */10;
  } else if (x >= 4190 && x <= 4192) {
    return /* NSM */6;
  } else if (x >= 4193 && x <= 4208) {
    return /* L */10;
  } else if (x >= 4209 && x <= 4212) {
    return /* NSM */6;
  } else if (x >= 4213 && x <= 4225 || x >= 4227 && x <= 4228) {
    return /* L */10;
  } else if (x >= 4229 && x <= 4230) {
    return /* NSM */6;
  } else if (x >= 4231 && x <= 4236 || x >= 4238 && x <= 4252 || x >= 4254 && x <= 4956) {
    return /* L */10;
  } else if (x >= 4957 && x <= 4959) {
    return /* NSM */6;
  } else if (x >= 4960 && x <= 5007) {
    return /* L */10;
  } else if (x >= 5008 && x <= 5023) {
    return /* ON */3;
  } else if (x >= 5024 && x <= 5119 || x >= 5121 && x <= 5759 || x >= 5761 && x <= 5786) {
    return /* L */10;
  } else if (x >= 5787 && x <= 5791) {
    return /* ON */3;
  } else if (x >= 5792 && x <= 5905) {
    return /* L */10;
  } else if (x >= 5906 && x <= 5919) {
    return /* NSM */6;
  } else if (x >= 5920 && x <= 5937) {
    return /* L */10;
  } else if (x >= 5938 && x <= 5940) {
    return /* NSM */6;
  } else if (x >= 5941 && x <= 5969) {
    return /* L */10;
  } else if (x >= 5970 && x <= 5983) {
    return /* NSM */6;
  } else if (x >= 5984 && x <= 6001) {
    return /* L */10;
  } else if (x >= 6002 && x <= 6015) {
    return /* NSM */6;
  } else if (x >= 6016 && x <= 6067) {
    return /* L */10;
  } else if (x >= 6068 && x <= 6069 || x >= 6071 && x <= 6077) {
    return /* NSM */6;
  } else if (x >= 6078 && x <= 6085 || x >= 6087 && x <= 6088) {
    return /* L */10;
  } else if (x >= 6089 && x <= 6099) {
    return /* NSM */6;
  } else if (x >= 6100 && x <= 6106) {
    return /* L */10;
  } else if (x >= 6109 && x <= 6111) {
    return /* NSM */6;
  } else if (x >= 6112 && x <= 6127) {
    return /* L */10;
  } else if (x >= 6128 && x <= 6154) {
    return /* ON */3;
  } else if (x >= 6155 && x <= 6157) {
    return /* NSM */6;
  } else if (x >= 6158 && x <= 6159) {
    return /* BN */0;
  } else if (x >= 6160 && x <= 6276) {
    return /* L */10;
  } else if (x >= 6277 && x <= 6278) {
    return /* NSM */6;
  } else if (x >= 6279 && x <= 6312 || x >= 6314 && x <= 6431) {
    return /* L */10;
  } else if (x >= 6432 && x <= 6434) {
    return /* NSM */6;
  } else if (x >= 6435 && x <= 6438) {
    return /* L */10;
  } else if (x >= 6439 && x <= 6440) {
    return /* NSM */6;
  } else if (x >= 6441 && x <= 6449 || x >= 6451 && x <= 6456) {
    return /* L */10;
  } else if (x >= 6457 && x <= 6463) {
    return /* NSM */6;
  } else if (x >= 6464 && x <= 6469) {
    return /* ON */3;
  } else if (x >= 6470 && x <= 6621) {
    return /* L */10;
  } else if (x >= 6622 && x <= 6655) {
    return /* ON */3;
  } else if (x >= 6656 && x <= 6678) {
    return /* L */10;
  } else if (x >= 6679 && x <= 6680) {
    return /* NSM */6;
  } else if (x >= 6681 && x <= 6682) {
    return /* L */10;
  } else if (x >= 6683 && x <= 6685) {
    return /* NSM */6;
  } else if (x >= 6686 && x <= 6741) {
    return /* L */10;
  } else if (x >= 6744 && x <= 6752) {
    return /* NSM */6;
  } else if (x >= 6755 && x <= 6756) {
    return /* L */10;
  } else if (x >= 6757 && x <= 6764) {
    return /* NSM */6;
  } else if (x >= 6765 && x <= 6770) {
    return /* L */10;
  } else if (x >= 6771 && x <= 6783) {
    return /* NSM */6;
  } else if (x >= 6784 && x <= 6831) {
    return /* L */10;
  } else if (x >= 6832 && x <= 6915) {
    return /* NSM */6;
  } else if (x >= 6916 && x <= 6963) {
    return /* L */10;
  } else if (x >= 6966 && x <= 6970) {
    return /* NSM */6;
  } else if (x >= 6973 && x <= 6977 || x >= 6979 && x <= 7018) {
    return /* L */10;
  } else if (x >= 7019 && x <= 7027) {
    return /* NSM */6;
  } else if (x >= 7028 && x <= 7039) {
    return /* L */10;
  } else if (x >= 7040 && x <= 7041) {
    return /* NSM */6;
  } else if (x >= 7042 && x <= 7073) {
    return /* L */10;
  } else if (x >= 7074 && x <= 7077) {
    return /* NSM */6;
  } else if (x >= 7078 && x <= 7079) {
    return /* L */10;
  } else if (x >= 7080 && x <= 7081 || x >= 7083 && x <= 7085) {
    return /* NSM */6;
  } else if (x >= 7086 && x <= 7141) {
    return /* L */10;
  } else if (x >= 7144 && x <= 7145) {
    return /* NSM */6;
  } else if (x >= 7146 && x <= 7148) {
    return /* L */10;
  } else if (x >= 7151 && x <= 7153) {
    return /* NSM */6;
  } else if (x >= 7154 && x <= 7211) {
    return /* L */10;
  } else if (x >= 7212 && x <= 7219) {
    return /* NSM */6;
  } else if (x >= 7220 && x <= 7221) {
    return /* L */10;
  } else if (x >= 7222 && x <= 7226) {
    return /* NSM */6;
  } else if (x >= 7227 && x <= 7375) {
    return /* L */10;
  } else if (x >= 7376 && x <= 7378 || x >= 7380 && x <= 7392 || x >= 7394 && x <= 7400) {
    return /* NSM */6;
  } else if (x >= 7401 && x <= 7404 || x >= 7406 && x <= 7411 || x >= 7413 && x <= 7415) {
    return /* L */10;
  } else if (x >= 7416 && x <= 7417) {
    return /* NSM */6;
  } else if (x >= 7418 && x <= 7615) {
    return /* L */10;
  } else if (x >= 7616 && x <= 7679) {
    return /* NSM */6;
  } else if (x >= 7680 && x <= 8124) {
    return /* L */10;
  } else if (x >= 8127 && x <= 8129) {
    return /* ON */3;
  } else if (x >= 8130 && x <= 8140) {
    return /* L */10;
  } else if (x >= 8141 && x <= 8143) {
    return /* ON */3;
  } else if (x >= 8144 && x <= 8156) {
    return /* L */10;
  } else if (x >= 8157 && x <= 8159) {
    return /* ON */3;
  } else if (x >= 8160 && x <= 8172) {
    return /* L */10;
  } else if (x >= 8173 && x <= 8177) {
    return /* ON */3;
  } else if (x >= 8178 && x <= 8188) {
    return /* L */10;
  } else if (x >= 8189 && x <= 8191) {
    return /* ON */3;
  } else if (x >= 8192 && x <= 8202) {
    return /* WS */7;
  } else if (x >= 8203 && x <= 8205) {
    return /* BN */0;
  } else if (x >= 8208 && x <= 8231) {
    return /* ON */3;
  } else if (x >= 8240 && x <= 8244) {
    return /* ET */11;
  } else if (x >= 8245 && x <= 8259 || x >= 8261 && x <= 8286) {
    return /* ON */3;
  } else if (x >= 8288 && x <= 8293 || x >= 8298 && x <= 8303) {
    return /* BN */0;
  } else if (x >= 8305 && x <= 8307) {
    return /* L */10;
  } else if (x >= 8308 && x <= 8313) {
    return /* EN */9;
  } else if (x >= 8314 && x <= 8315) {
    return /* ES */2;
  } else if (x >= 8316 && x <= 8318) {
    return /* ON */3;
  } else if (x >= 8320 && x <= 8329) {
    return /* EN */9;
  } else if (x >= 8330 && x <= 8331) {
    return /* ES */2;
  } else if (x >= 8332 && x <= 8335) {
    return /* ON */3;
  } else if (x >= 8336 && x <= 8351) {
    return /* L */10;
  } else if (x >= 8352 && x <= 8399) {
    return /* ET */11;
  } else if (x >= 8400 && x <= 8447) {
    return /* NSM */6;
  } else if (x >= 8448 && x <= 8449 || x >= 8451 && x <= 8454 || x >= 8456 && x <= 8457) {
    return /* ON */3;
  } else if (x >= 8458 && x <= 8467) {
    return /* L */10;
  } else if (x >= 8470 && x <= 8472) {
    return /* ON */3;
  } else if (x >= 8473 && x <= 8477) {
    return /* L */10;
  } else if (x >= 8478 && x <= 8483) {
    return /* ON */3;
  } else if (x >= 8490 && x <= 8493 || x >= 8495 && x <= 8505) {
    return /* L */10;
  } else if (x >= 8506 && x <= 8507) {
    return /* ON */3;
  } else if (x >= 8508 && x <= 8511) {
    return /* L */10;
  } else if (x >= 8512 && x <= 8516) {
    return /* ON */3;
  } else if (x >= 8517 && x <= 8521) {
    return /* L */10;
  } else if (x >= 8522 && x <= 8525) {
    return /* ON */3;
  } else if (x >= 8526 && x <= 8527) {
    return /* L */10;
  } else if (x >= 8528 && x <= 8543) {
    return /* ON */3;
  } else if (x >= 8544 && x <= 8584) {
    return /* L */10;
  } else if (x >= 8585 && x <= 8721 || x >= 8724 && x <= 9013) {
    return /* ON */3;
  } else if (x >= 9014 && x <= 9082) {
    return /* L */10;
  } else if (x >= 9083 && x <= 9108 || x >= 9110 && x <= 9351) {
    return /* ON */3;
  } else if (x >= 9352 && x <= 9371) {
    return /* EN */9;
  } else if (x >= 9372 && x <= 9449) {
    return /* L */10;
  } else if (x >= 9450 && x <= 9899 || x >= 9901 && x <= 10239) {
    return /* ON */3;
  } else if (x >= 10240 && x <= 10495) {
    return /* L */10;
  } else if (x >= 10496 && x <= 11263) {
    return /* ON */3;
  } else if (x >= 11264 && x <= 11492) {
    return /* L */10;
  } else if (x >= 11493 && x <= 11498) {
    return /* ON */3;
  } else if (x >= 11499 && x <= 11502) {
    return /* L */10;
  } else if (x >= 11503 && x <= 11505) {
    return /* NSM */6;
  } else if (x >= 11506 && x <= 11512) {
    return /* L */10;
  } else if (x >= 11513 && x <= 11519) {
    return /* ON */3;
  } else if (x >= 11520 && x <= 11646 || x >= 11648 && x <= 11743) {
    return /* L */10;
  } else if (x >= 11744 && x <= 11775) {
    return /* NSM */6;
  } else if (x >= 11776 && x <= 12287 || x >= 12289 && x <= 12292) {
    return /* ON */3;
  } else if (x >= 12293 && x <= 12295) {
    return /* L */10;
  } else if (x >= 12296 && x <= 12320) {
    return /* ON */3;
  } else if (x >= 12321 && x <= 12329) {
    return /* L */10;
  } else if (x >= 12330 && x <= 12333) {
    return /* NSM */6;
  } else if (x >= 12334 && x <= 12335 || x >= 12337 && x <= 12341) {
    return /* L */10;
  } else if (x >= 12342 && x <= 12343) {
    return /* ON */3;
  } else if (x >= 12344 && x <= 12348) {
    return /* L */10;
  } else if (x >= 12349 && x <= 12352) {
    return /* ON */3;
  } else if (x >= 12353 && x <= 12440) {
    return /* L */10;
  } else if (x >= 12441 && x <= 12442) {
    return /* NSM */6;
  } else if (x >= 12443 && x <= 12444) {
    return /* ON */3;
  } else if (x >= 12445 && x <= 12447 || x >= 12449 && x <= 12538 || x >= 12540 && x <= 12735) {
    return /* L */10;
  } else if (x >= 12736 && x <= 12783) {
    return /* ON */3;
  } else if (x >= 12784 && x <= 12828) {
    return /* L */10;
  } else if (x >= 12829 && x <= 12831) {
    return /* ON */3;
  } else if (x >= 12832 && x <= 12879) {
    return /* L */10;
  } else if (x >= 12880 && x <= 12895) {
    return /* ON */3;
  } else if (x >= 12896 && x <= 12923) {
    return /* L */10;
  } else if (x >= 12924 && x <= 12926) {
    return /* ON */3;
  } else if (x >= 12927 && x <= 12976) {
    return /* L */10;
  } else if (x >= 12977 && x <= 12991) {
    return /* ON */3;
  } else if (x >= 12992 && x <= 13003) {
    return /* L */10;
  } else if (x >= 13004 && x <= 13007) {
    return /* ON */3;
  } else if (x >= 13008 && x <= 13174) {
    return /* L */10;
  } else if (x >= 13175 && x <= 13178) {
    return /* ON */3;
  } else if (x >= 13179 && x <= 13277) {
    return /* L */10;
  } else if (x >= 13278 && x <= 13279) {
    return /* ON */3;
  } else if (x >= 13280 && x <= 13310 || x >= 13312 && x <= 19903) {
    return /* L */10;
  } else if (x >= 19904 && x <= 19967) {
    return /* ON */3;
  } else if (x >= 19968 && x <= 42127) {
    return /* L */10;
  } else if (x >= 42128 && x <= 42191) {
    return /* ON */3;
  } else if (x >= 42192 && x <= 42508) {
    return /* L */10;
  } else if (x >= 42509 && x <= 42511) {
    return /* ON */3;
  } else if (x >= 42512 && x <= 42606) {
    return /* L */10;
  } else if (x >= 42607 && x <= 42610 || x >= 42612 && x <= 42621) {
    return /* NSM */6;
  } else if (x >= 42622 && x <= 42623) {
    return /* ON */3;
  } else if (x >= 42624 && x <= 42653) {
    return /* L */10;
  } else if (x >= 42654 && x <= 42655) {
    return /* NSM */6;
  } else if (x >= 42656 && x <= 42735) {
    return /* L */10;
  } else if (x >= 42736 && x <= 42737) {
    return /* NSM */6;
  } else if (x >= 42738 && x <= 42751) {
    return /* L */10;
  } else if (x >= 42752 && x <= 42785) {
    return /* ON */3;
  } else if (x >= 42786 && x <= 42887 || x >= 42889 && x <= 43009 || x >= 43011 && x <= 43013 || x >= 43015 && x <= 43018 || x >= 43020 && x <= 43044) {
    return /* L */10;
  } else if (x >= 43045 && x <= 43046) {
    return /* NSM */6;
  } else if (x >= 43048 && x <= 43055) {
    return /* ON */3;
  } else if (x >= 43056 && x <= 43063) {
    return /* L */10;
  } else if (x >= 43064 && x <= 43071) {
    return /* ET */11;
  } else if (x >= 43072 && x <= 43123) {
    return /* L */10;
  } else if (x >= 43124 && x <= 43135) {
    return /* ON */3;
  } else if (x >= 43136 && x <= 43203) {
    return /* L */10;
  } else if (x >= 43204 && x <= 43213) {
    return /* NSM */6;
  } else if (x >= 43214 && x <= 43231) {
    return /* L */10;
  } else if (x >= 43232 && x <= 43249) {
    return /* NSM */6;
  } else if (x >= 43250 && x <= 43262 || x >= 43264 && x <= 43301) {
    return /* L */10;
  } else if (x >= 43302 && x <= 43309) {
    return /* NSM */6;
  } else if (x >= 43310 && x <= 43334) {
    return /* L */10;
  } else if (x >= 43335 && x <= 43345) {
    return /* NSM */6;
  } else if (x >= 43346 && x <= 43391) {
    return /* L */10;
  } else if (x >= 43392 && x <= 43394) {
    return /* NSM */6;
  } else if (x >= 43395 && x <= 43442 || x >= 43444 && x <= 43445) {
    return /* L */10;
  } else if (x >= 43446 && x <= 43449) {
    return /* NSM */6;
  } else if (x >= 43450 && x <= 43451) {
    return /* L */10;
  } else if (x >= 43452 && x <= 43453) {
    return /* NSM */6;
  } else if (x >= 43454 && x <= 43492 || x >= 43494 && x <= 43560) {
    return /* L */10;
  } else if (x >= 43561 && x <= 43566) {
    return /* NSM */6;
  } else if (x >= 43567 && x <= 43568) {
    return /* L */10;
  } else if (x >= 43569 && x <= 43570) {
    return /* NSM */6;
  } else if (x >= 43571 && x <= 43572) {
    return /* L */10;
  } else if (x >= 43573 && x <= 43583) {
    return /* NSM */6;
  } else if (x >= 43584 && x <= 43586 || x >= 43588 && x <= 43595 || x >= 43597 && x <= 43643 || x >= 43645 && x <= 43695) {
    return /* L */10;
  } else if (x >= 43698 && x <= 43700) {
    return /* NSM */6;
  } else if (x >= 43701 && x <= 43702) {
    return /* L */10;
  } else if (x >= 43703 && x <= 43704) {
    return /* NSM */6;
  } else if (x >= 43705 && x <= 43709) {
    return /* L */10;
  } else if (x >= 43710 && x <= 43711) {
    return /* NSM */6;
  } else if (x >= 43714 && x <= 43755) {
    return /* L */10;
  } else if (x >= 43756 && x <= 43757) {
    return /* NSM */6;
  } else if (x >= 43758 && x <= 43765) {
    return /* L */10;
  } else if (x >= 43766 && x <= 43776) {
    return /* NSM */6;
  } else if (x >= 43777 && x <= 44004 || x >= 44006 && x <= 44007 || x >= 44009 && x <= 44012) {
    return /* L */10;
  } else if (x >= 44013 && x <= 44015) {
    return /* NSM */6;
  } else if (x >= 44016 && x <= 64284) {
    return /* L */10;
  } else if (x >= 64287 && x <= 64296 || x >= 64298 && x <= 64335) {
    return /* R */4;
  } else if (x >= 64336 && x <= 64829) {
    return /* AL */5;
  } else if (x >= 64830 && x <= 64847) {
    return /* ON */3;
  } else if (x >= 64848 && x <= 65020) {
    return /* AL */5;
  } else if (x >= 65021 && x <= 65023) {
    return /* ON */3;
  } else if (x >= 65024 && x <= 65039) {
    return /* NSM */6;
  } else if (x >= 65040 && x <= 65055) {
    return /* ON */3;
  } else if (x >= 65056 && x <= 65071) {
    return /* NSM */6;
  } else if (x >= 65072 && x <= 65103) {
    return /* ON */3;
  } else if (x >= 65106 && x <= 65107) {
    return /* CS */8;
  } else if (x >= 65110 && x <= 65118 || x >= 65120 && x <= 65121) {
    return /* ON */3;
  } else if (x >= 65122 && x <= 65123) {
    return /* ES */2;
  } else if (x >= 65124 && x <= 65128) {
    return /* ON */3;
  } else if (x >= 65129 && x <= 65130) {
    return /* ET */11;
  } else if (x >= 65131 && x <= 65135) {
    return /* ON */3;
  } else if (x >= 65136 && x <= 65278) {
    return /* AL */5;
  } else if (x >= 65279 && x <= 65280) {
    return /* BN */0;
  } else if (x >= 65281 && x <= 65282) {
    return /* ON */3;
  } else if (x >= 65283 && x <= 65285) {
    return /* ET */11;
  } else if (x >= 65286 && x <= 65290) {
    return /* ON */3;
  } else if (x >= 65294 && x <= 65295) {
    return /* CS */8;
  } else if (x >= 65296 && x <= 65305) {
    return /* EN */9;
  } else if (x >= 65307 && x <= 65312) {
    return /* ON */3;
  } else if (x >= 65313 && x <= 65338) {
    return /* L */10;
  } else if (x >= 65339 && x <= 65344) {
    return /* ON */3;
  } else if (x >= 65345 && x <= 65370) {
    return /* L */10;
  } else if (x >= 65371 && x <= 65381) {
    return /* ON */3;
  } else if (x >= 65382 && x <= 65503) {
    return /* L */10;
  } else if (x >= 65504 && x <= 65505) {
    return /* ET */11;
  } else if (x >= 65506 && x <= 65508) {
    return /* ON */3;
  } else if (x >= 65509 && x <= 65511) {
    return /* ET */11;
  } else if (x >= 65512 && x <= 65535) {
    return /* ON */3;
  } else if (x >= 65536 && x <= 65792 || x >= 65794 && x <= 65855) {
    return /* L */10;
  } else if (x >= 65856 && x <= 65932) {
    return /* ON */3;
  } else if (x >= 65933 && x <= 65935) {
    return /* L */10;
  } else if (x >= 65936 && x <= 65999) {
    return /* ON */3;
  } else if (x >= 66000 && x <= 66044) {
    return /* L */10;
  } else if (x >= 66045 && x <= 66175) {
    return /* NSM */6;
  } else if (x >= 66176 && x <= 66271) {
    return /* L */10;
  } else if (x >= 66273 && x <= 66303) {
    return /* EN */9;
  } else if (x >= 66304 && x <= 66421) {
    return /* L */10;
  } else if (x >= 66422 && x <= 66431) {
    return /* NSM */6;
  } else if (x >= 66432 && x <= 67583) {
    return /* L */10;
  } else if (x >= 67584 && x <= 67870 || x >= 67872 && x <= 68096) {
    return /* R */4;
  } else if (x >= 68097 && x <= 68111) {
    return /* NSM */6;
  } else if (x >= 68112 && x <= 68151) {
    return /* R */4;
  } else if (x >= 68152 && x <= 68159) {
    return /* NSM */6;
  } else if (x >= 68160 && x <= 68324) {
    return /* R */4;
  } else if (x >= 68325 && x <= 68330) {
    return /* NSM */6;
  } else if (x >= 68331 && x <= 68408) {
    return /* R */4;
  } else if (x >= 68409 && x <= 68415) {
    return /* ON */3;
  } else if (x >= 68416 && x <= 68863) {
    return /* R */4;
  } else if (x >= 68864 && x <= 68899) {
    return /* AL */5;
  } else if (x >= 68900 && x <= 68911) {
    return /* NSM */6;
  } else if (x >= 68912 && x <= 69375) {
    return /* AN */1;
  } else if (x >= 69376 && x <= 69423) {
    return /* R */4;
  } else if (x >= 69424 && x <= 69445) {
    return /* AL */5;
  } else if (x >= 69446 && x <= 69456) {
    return /* NSM */6;
  } else if (x >= 69457 && x <= 69599) {
    return /* AL */5;
  } else if (x >= 69600 && x <= 69631) {
    return /* R */4;
  } else if (x >= 69634 && x <= 69687) {
    return /* L */10;
  } else if (x >= 69688 && x <= 69702) {
    return /* NSM */6;
  } else if (x >= 69703 && x <= 69713) {
    return /* L */10;
  } else if (x >= 69714 && x <= 69733) {
    return /* ON */3;
  } else if (x >= 69734 && x <= 69758) {
    return /* L */10;
  } else if (x >= 69759 && x <= 69761) {
    return /* NSM */6;
  } else if (x >= 69762 && x <= 69810) {
    return /* L */10;
  } else if (x >= 69811 && x <= 69814) {
    return /* NSM */6;
  } else if (x >= 69815 && x <= 69816) {
    return /* L */10;
  } else if (x >= 69817 && x <= 69818) {
    return /* NSM */6;
  } else if (x >= 69819 && x <= 69887) {
    return /* L */10;
  } else if (x >= 69888 && x <= 69890) {
    return /* NSM */6;
  } else if (x >= 69891 && x <= 69926) {
    return /* L */10;
  } else if (x >= 69927 && x <= 69931 || x >= 69933 && x <= 69941) {
    return /* NSM */6;
  } else if (x >= 69942 && x <= 70002 || x >= 70004 && x <= 70015) {
    return /* L */10;
  } else if (x >= 70016 && x <= 70017) {
    return /* NSM */6;
  } else if (x >= 70018 && x <= 70069) {
    return /* L */10;
  } else if (x >= 70070 && x <= 70078) {
    return /* NSM */6;
  } else if (x >= 70079 && x <= 70088) {
    return /* L */10;
  } else if (x >= 70089 && x <= 70092) {
    return /* NSM */6;
  } else if (x >= 70093 && x <= 70190) {
    return /* L */10;
  } else if (x >= 70191 && x <= 70193) {
    return /* NSM */6;
  } else if (x >= 70194 && x <= 70195) {
    return /* L */10;
  } else if (x >= 70198 && x <= 70199) {
    return /* NSM */6;
  } else if (x >= 70200 && x <= 70205) {
    return /* L */10;
  } else if (x >= 70206 && x <= 70271) {
    return /* NSM */6;
  } else if (x >= 70272 && x <= 70366 || x >= 70368 && x <= 70370) {
    return /* L */10;
  } else if (x >= 70371 && x <= 70383) {
    return /* NSM */6;
  } else if (x >= 70384 && x <= 70399) {
    return /* L */10;
  } else if (x >= 70400 && x <= 70401) {
    return /* NSM */6;
  } else if (x >= 70402 && x <= 70458) {
    return /* L */10;
  } else if (x >= 70459 && x <= 70460) {
    return /* NSM */6;
  } else if (x >= 70461 && x <= 70463 || x >= 70465 && x <= 70501) {
    return /* L */10;
  } else if (x >= 70502 && x <= 70655) {
    return /* NSM */6;
  } else if (x >= 70656 && x <= 70711) {
    return /* L */10;
  } else if (x >= 70712 && x <= 70719) {
    return /* NSM */6;
  } else if (x >= 70720 && x <= 70721) {
    return /* L */10;
  } else if (x >= 70722 && x <= 70724) {
    return /* NSM */6;
  } else if (x >= 70727 && x <= 70749 || x >= 70751 && x <= 70834) {
    return /* L */10;
  } else if (x >= 70835 && x <= 70840) {
    return /* NSM */6;
  } else if (x >= 70843 && x <= 70846) {
    return /* L */10;
  } else if (x >= 70847 && x <= 70848 || x >= 70850 && x <= 70851) {
    return /* NSM */6;
  } else if (x >= 70852 && x <= 71089) {
    return /* L */10;
  } else if (x >= 71090 && x <= 71095) {
    return /* NSM */6;
  } else if (x >= 71096 && x <= 71099) {
    return /* L */10;
  } else if (x >= 71100 && x <= 71101 || x >= 71103 && x <= 71104) {
    return /* NSM */6;
  } else if (x >= 71105 && x <= 71131) {
    return /* L */10;
  } else if (x >= 71132 && x <= 71167) {
    return /* NSM */6;
  } else if (x >= 71168 && x <= 71218) {
    return /* L */10;
  } else if (x >= 71219 && x <= 71226) {
    return /* NSM */6;
  } else if (x >= 71227 && x <= 71228) {
    return /* L */10;
  } else if (x >= 71231 && x <= 71232) {
    return /* NSM */6;
  } else if (x >= 71233 && x <= 71263) {
    return /* L */10;
  } else if (x >= 71264 && x <= 71295) {
    return /* ON */3;
  } else if (x >= 71296 && x <= 71338 || x >= 71342 && x <= 71343) {
    return /* L */10;
  } else if (x >= 71344 && x <= 71349) {
    return /* NSM */6;
  } else if (x >= 71352 && x <= 71452) {
    return /* L */10;
  } else if (x >= 71453 && x <= 71455) {
    return /* NSM */6;
  } else if (x >= 71456 && x <= 71457) {
    return /* L */10;
  } else if (x >= 71458 && x <= 71461 || x >= 71463 && x <= 71471) {
    return /* NSM */6;
  } else if (x >= 71472 && x <= 71726) {
    return /* L */10;
  } else if (x >= 71727 && x <= 71735 || x >= 71737 && x <= 71738) {
    return /* NSM */6;
  } else if (x >= 71739 && x <= 72147) {
    return /* L */10;
  } else if (x >= 72148 && x <= 72155) {
    return /* NSM */6;
  } else if (x >= 72156 && x <= 72159 || x >= 72161 && x <= 72192) {
    return /* L */10;
  } else if (x >= 72193 && x <= 72198) {
    return /* NSM */6;
  } else if (x >= 72199 && x <= 72200) {
    return /* L */10;
  } else if (x >= 72201 && x <= 72202) {
    return /* NSM */6;
  } else if (x >= 72203 && x <= 72242) {
    return /* L */10;
  } else if (x >= 72243 && x <= 72248) {
    return /* NSM */6;
  } else if (x >= 72249 && x <= 72250) {
    return /* L */10;
  } else if (x >= 72251 && x <= 72254) {
    return /* NSM */6;
  } else if (x >= 72255 && x <= 72262) {
    return /* L */10;
  } else if (x >= 72263 && x <= 72271 || x >= 72273 && x <= 72278) {
    return /* NSM */6;
  } else if (x >= 72279 && x <= 72280) {
    return /* L */10;
  } else if (x >= 72281 && x <= 72283) {
    return /* NSM */6;
  } else if (x >= 72284 && x <= 72329) {
    return /* L */10;
  } else if (x >= 72330 && x <= 72342 || x >= 72344 && x <= 72345) {
    return /* NSM */6;
  } else if (x >= 72346 && x <= 72751) {
    return /* L */10;
  } else if (x >= 72752 && x <= 72765) {
    return /* NSM */6;
  } else if (x >= 72766 && x <= 72849) {
    return /* L */10;
  } else if (x >= 72850 && x <= 72872 || x >= 72874 && x <= 72880 || x >= 72882 && x <= 72883 || x >= 72885 && x <= 72959) {
    return /* NSM */6;
  } else if (x >= 72960 && x <= 73008) {
    return /* L */10;
  } else if (x >= 73009 && x <= 73029 || x >= 73031 && x <= 73039) {
    return /* NSM */6;
  } else if (x >= 73040 && x <= 73103) {
    return /* L */10;
  } else if (x >= 73104 && x <= 73106) {
    return /* NSM */6;
  } else if (x >= 73107 && x <= 73108 || x >= 73112 && x <= 73458) {
    return /* L */10;
  } else if (x >= 73459 && x <= 73460) {
    return /* NSM */6;
  } else if (x >= 73461 && x <= 73684) {
    return /* L */10;
  } else if (x >= 73685 && x <= 73692) {
    return /* ON */3;
  } else if (x >= 73693 && x <= 73696) {
    return /* ET */11;
  } else if (x >= 73697 && x <= 73726) {
    return /* ON */3;
  } else if (x >= 73727 && x <= 92911) {
    return /* L */10;
  } else if (x >= 92912 && x <= 92916) {
    return /* NSM */6;
  } else if (x >= 92917 && x <= 92975) {
    return /* L */10;
  } else if (x >= 92976 && x <= 92982) {
    return /* NSM */6;
  } else if (x >= 92983 && x <= 94030 || x >= 94032 && x <= 94094) {
    return /* L */10;
  } else if (x >= 94095 && x <= 94098) {
    return /* NSM */6;
  } else if (x >= 94099 && x <= 94177 || x >= 94179 && x <= 113820) {
    return /* L */10;
  } else if (x >= 113821 && x <= 113822) {
    return /* NSM */6;
  } else if (x >= 113824 && x <= 118783) {
    return /* BN */0;
  } else if (x >= 118784 && x <= 119142) {
    return /* L */10;
  } else if (x >= 119143 && x <= 119145) {
    return /* NSM */6;
  } else if (x >= 119146 && x <= 119154) {
    return /* L */10;
  } else if (x >= 119155 && x <= 119162) {
    return /* BN */0;
  } else if (x >= 119163 && x <= 119170) {
    return /* NSM */6;
  } else if (x >= 119171 && x <= 119172) {
    return /* L */10;
  } else if (x >= 119173 && x <= 119179) {
    return /* NSM */6;
  } else if (x >= 119180 && x <= 119209) {
    return /* L */10;
  } else if (x >= 119210 && x <= 119213) {
    return /* NSM */6;
  } else if (x >= 119214 && x <= 119295) {
    return /* L */10;
  } else if (x >= 119296 && x <= 119361) {
    return /* ON */3;
  } else if (x >= 119362 && x <= 119364) {
    return /* NSM */6;
  } else if (x >= 119365 && x <= 119519) {
    return /* ON */3;
  } else if (x >= 119520 && x <= 119551) {
    return /* L */10;
  } else if (x >= 119552 && x <= 119647) {
    return /* ON */3;
  } else if (x >= 119648 && x <= 120538 || x >= 120540 && x <= 120596 || x >= 120598 && x <= 120654 || x >= 120656 && x <= 120712 || x >= 120714 && x <= 120770 || x >= 120772 && x <= 120781) {
    return /* L */10;
  } else if (x >= 120782 && x <= 120831) {
    return /* EN */9;
  } else if (x >= 120832 && x <= 121343) {
    return /* L */10;
  } else if (x >= 121344 && x <= 121398) {
    return /* NSM */6;
  } else if (x >= 121399 && x <= 121402) {
    return /* L */10;
  } else if (x >= 121403 && x <= 121452) {
    return /* NSM */6;
  } else if (x >= 121453 && x <= 121460 || x >= 121462 && x <= 121475 || x >= 121477 && x <= 121498) {
    return /* L */10;
  } else if (x >= 121499 && x <= 123135) {
    return /* NSM */6;
  } else if (x >= 123136 && x <= 123183) {
    return /* L */10;
  } else if (x >= 123184 && x <= 123190) {
    return /* NSM */6;
  } else if (x >= 123191 && x <= 123627) {
    return /* L */10;
  } else if (x >= 123628 && x <= 123631) {
    return /* NSM */6;
  } else if (x >= 123632 && x <= 123646) {
    return /* L */10;
  } else if (x >= 123647 && x <= 124927) {
    return /* ET */11;
  } else if (x >= 124928 && x <= 125135) {
    return /* R */4;
  } else if (x >= 125136 && x <= 125183) {
    return /* NSM */6;
  } else if (x >= 125184 && x <= 125251) {
    return /* R */4;
  } else if (x >= 125252 && x <= 125258) {
    return /* NSM */6;
  } else if (x >= 125259 && x <= 126064) {
    return /* R */4;
  } else if (x >= 126065 && x <= 126703) {
    return /* AL */5;
  } else if (x >= 126704 && x <= 127231) {
    return /* ON */3;
  } else if (x >= 127232 && x <= 127242) {
    return /* EN */9;
  } else if (x >= 127243 && x <= 127247) {
    return /* ON */3;
  } else if (x >= 127248 && x <= 127278 || x >= 127280 && x <= 127337) {
    return /* L */10;
  } else if (x >= 127338 && x <= 127343) {
    return /* ON */3;
  } else if (x >= 127344 && x <= 127583) {
    return /* L */10;
  } else if (x >= 127584 && x <= 131071) {
    return /* ON */3;
  } else if (x >= 131072 && x <= 917504) {
    return /* L */10;
  } else if (x >= 917505 && x <= 917759) {
    return /* BN */0;
  } else if (x >= 917760 && x <= 983039) {
    return /* NSM */6;
  } else {
    return /* Illegal */13;
  }
}

function testRtlProps(directionList) {
  var allowList = List.map((function (index) {
          var propAllow = List.map((function (prop) {
                  return index === prop;
                }), /* :: */[
                /* R */4,
                /* :: */[
                  /* AL */5,
                  /* :: */[
                    /* AN */1,
                    /* :: */[
                      /* EN */9,
                      /* :: */[
                        /* ES */2,
                        /* :: */[
                          /* CS */8,
                          /* :: */[
                            /* ET */11,
                            /* :: */[
                              /* ON */3,
                              /* :: */[
                                /* BN */0,
                                /* :: */[
                                  /* NSM */6,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]);
          return List.mem(true, propAllow);
        }), directionList);
  return !List.mem(false, allowList);
}

function testEnAndAn(directionList) {
  var en = List.mem(/* EN */9, directionList);
  var an = List.mem(/* AN */1, directionList);
  return !(en && an);
}

function testEndR(_directionList) {
  while(true) {
    var directionList = _directionList;
    if (directionList) {
      switch (directionList[0]) {
        case 6 : 
            _directionList = directionList[1];
            continue ;
        case 1 : 
        case 4 : 
        case 5 : 
        case 9 : 
            return true;
        case 0 : 
        case 2 : 
        case 3 : 
        case 7 : 
        case 8 : 
        case 10 : 
        case 11 : 
        case 12 : 
        case 13 : 
            return false;
        
      }
    } else {
      return true;
    }
  };
}

function testEndL(_directionList) {
  while(true) {
    var directionList = _directionList;
    if (directionList) {
      var _head = directionList[0];
      if (_head >= 11) {
        return false;
      } else {
        switch (_head) {
          case 6 : 
              _directionList = directionList[1];
              continue ;
          case 0 : 
          case 2 : 
          case 3 : 
          case 4 : 
          case 5 : 
          case 7 : 
          case 8 : 
              return false;
          case 1 : 
          case 9 : 
          case 10 : 
              return true;
          
        }
      }
    } else {
      return true;
    }
  };
}

function testLtrProps(directionList) {
  var allowList = List.map((function (index) {
          var propAllow = List.map((function (prop) {
                  return index === prop;
                }), /* :: */[
                /* L */10,
                /* :: */[
                  /* EN */9,
                  /* :: */[
                    /* ES */2,
                    /* :: */[
                      /* CS */8,
                      /* :: */[
                        /* ET */11,
                        /* :: */[
                          /* ON */3,
                          /* :: */[
                            /* BN */0,
                            /* :: */[
                              /* NSM */6,
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]);
          return List.mem(true, propAllow);
        }), directionList);
  return !List.mem(false, allowList);
}

function validate(codePointList) {
  var directionList = List.map(getDirectionProperty, codePointList);
  var _direction = getDirectionProperty(List.hd(codePointList));
  if (_direction >= 11) {
    return false;
  } else {
    switch (_direction) {
      case 4 : 
      case 5 : 
          var directionList$1 = List.tl(directionList);
          var rtlAllow = testRtlProps(directionList$1);
          var noEnAndAn = testEnAndAn(directionList$1);
          var testEnd = testEndR(List.rev(directionList$1));
          if (rtlAllow && noEnAndAn) {
            return testEnd;
          } else {
            return false;
          }
      case 0 : 
      case 1 : 
      case 2 : 
      case 3 : 
      case 6 : 
      case 7 : 
      case 8 : 
      case 9 : 
          return false;
      case 10 : 
          var directionList$2 = List.tl(directionList);
          var ltrAllow = testLtrProps(directionList$2);
          var testEnd$1 = testEndL(List.rev(directionList$2));
          if (ltrAllow) {
            return testEnd$1;
          } else {
            return false;
          }
      
    }
  }
}

exports.validate = validate;
exports.getDirectionProperty = getDirectionProperty;
/* No side effect */
