// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function virama(param) {
  return true;
}

function contextO(codePointList) {
  var _codePointList = codePointList;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var codePointList$1 = _codePointList;
    if (codePointList$1) {
      var tail = codePointList$1[1];
      var cp1 = codePointList$1[0];
      var exit = 0;
      if (tail) {
        var tail$1 = tail[1];
        var cp2 = tail[0];
        if (cp2 === 8204) {
          _acc = Pervasives.$at(/* :: */[
                cp2,
                /* :: */[
                  cp1,
                  /* [] */0
                ]
              ], acc);
          _codePointList = tail$1;
          continue ;
        } else if (cp2 === 8205) {
          _acc = Pervasives.$at(/* :: */[
                cp2,
                /* :: */[
                  cp1,
                  /* [] */0
                ]
              ], acc);
          _codePointList = tail$1;
          continue ;
        } else {
          exit = 1;
        }
      } else {
        exit = 1;
      }
      if (exit === 1) {
        _acc = Pervasives.$at(/* :: */[
              cp1,
              /* [] */0
            ], acc);
        _codePointList = tail;
        continue ;
      }
      
    } else {
      return true;
    }
  };
}

var zeroWidthNonJoiner = 8204;

var zeroWidthJoiner = 8205;

var middleDot = 183;

var greekNumeralSign = 885;

var hebrewPunctuationGeresh = 1523;

var hebrewPunctuationGereshayim = 1524;

var katakanaMiddleDot = 12539;

var arabicIndicDigits = /* :: */[
  1632,
  /* :: */[
    1641,
    /* [] */0
  ]
];

var zwnjRegexp = true;

exports.zeroWidthNonJoiner = zeroWidthNonJoiner;
exports.zeroWidthJoiner = zeroWidthJoiner;
exports.middleDot = middleDot;
exports.greekNumeralSign = greekNumeralSign;
exports.hebrewPunctuationGeresh = hebrewPunctuationGeresh;
exports.hebrewPunctuationGereshayim = hebrewPunctuationGereshayim;
exports.katakanaMiddleDot = katakanaMiddleDot;
exports.arabicIndicDigits = arabicIndicDigits;
exports.virama = virama;
exports.zwnjRegexp = zwnjRegexp;
exports.contextO = contextO;
/* No side effect */
