// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var PrecisCodePoints$BsPrecis = require("./PrecisCodePoints.bs.js");

function arabicIndicDigits(param) {
  return List.fold_left((function (v, cp) {
                if (v) {
                  return !(cp >= 1776 && cp <= 1785);
                } else {
                  return false;
                }
              }), true, param);
}

function context(codePointList) {
  var _codePointList = codePointList;
  var _precisCodePoints = List.map(PrecisCodePoints$BsPrecis.fromCodePoint, codePointList);
  var _acc = /* [] */0;
  var _precisAcc = /* [] */0;
  while(true) {
    var precisAcc = _precisAcc;
    var acc = _acc;
    var precisCodePoints = _precisCodePoints;
    var codePointList$1 = _codePointList;
    if (precisCodePoints) {
      var precisTail = precisCodePoints[1];
      var cc = precisCodePoints[0];
      var exit = 0;
      if (precisTail) {
        var match = precisTail[0];
        if (match >= 2) {
          exit = 1;
        } else {
          var match$1 = precisTail[1];
          if (match$1) {
            var precisTail$1 = match$1[1];
            var cc2 = match$1[0];
            if (codePointList$1) {
              var match$2 = codePointList$1[1];
              if (match$2) {
                var cpTail = match$2[1];
                var cp2 = match$2[0];
                var cp1 = codePointList$1[0];
                var exit$1 = 0;
                var exit$2 = 0;
                if (cpTail && cp2 === 183) {
                  var cp3 = cpTail[0];
                  if (cp1 === 183 && cp1 === cp3) {
                    _precisAcc = Pervasives.$at(/* :: */[
                          cc2,
                          /* :: */[
                            match,
                            /* :: */[
                              cc,
                              /* [] */0
                            ]
                          ]
                        ], precisAcc);
                    _acc = Pervasives.$at(/* :: */[
                          cp3,
                          /* :: */[
                            cp2,
                            /* :: */[
                              cp1,
                              /* [] */0
                            ]
                          ]
                        ], acc);
                    _precisCodePoints = precisTail$1;
                    _codePointList = cpTail[1];
                    continue ;
                  } else {
                    return false;
                  }
                } else {
                  exit$2 = 3;
                }
                if (exit$2 === 3) {
                  if (cp2 === 8204 || cp2 === 8205 || cp2 === 1523 || cp2 === 1524 || cpTail && cp2 === 885) {
                    return false;
                  } else {
                    exit$1 = 2;
                  }
                }
                if (exit$1 === 2) {
                  if (cp2 === 12539) {
                    if ((Pervasives.$at(acc, codePointList$1), false) || (Pervasives.$at(acc, codePointList$1), false) || (Pervasives.$at(acc, codePointList$1), false)) {
                      _precisAcc = Pervasives.$at(/* :: */[
                            match,
                            /* :: */[
                              cc,
                              /* [] */0
                            ]
                          ], precisAcc);
                      _acc = Pervasives.$at(/* :: */[
                            cp2,
                            /* :: */[
                              cp1,
                              /* [] */0
                            ]
                          ], acc);
                      _precisCodePoints = Pervasives.$at(/* :: */[
                            cc2,
                            /* [] */0
                          ], precisTail$1);
                      _codePointList = cpTail;
                      continue ;
                    } else {
                      return false;
                    }
                  } else if (cp2 >= 1632 && cp2 <= 1641 && arabicIndicDigits(Pervasives.$at(acc, codePointList$1))) {
                    _precisAcc = Pervasives.$at(/* :: */[
                          match,
                          /* :: */[
                            cc,
                            /* [] */0
                          ]
                        ], precisAcc);
                    _acc = Pervasives.$at(/* :: */[
                          cp2,
                          /* :: */[
                            cp1,
                            /* [] */0
                          ]
                        ], acc);
                    _precisCodePoints = Pervasives.$at(/* :: */[
                          cc2,
                          /* [] */0
                        ], precisTail$1);
                    _codePointList = cpTail;
                    continue ;
                  } else {
                    return false;
                  }
                }
                
              } else {
                return false;
              }
            } else {
              return false;
            }
          } else {
            exit = 1;
          }
        }
      } else {
        exit = 1;
      }
      if (exit === 1) {
        _precisAcc = Pervasives.$at(/* :: */[
              cc,
              /* [] */0
            ], precisAcc);
        _acc = Pervasives.$at(/* :: */[
              List.hd(codePointList$1),
              /* [] */0
            ], acc);
        _precisCodePoints = precisTail;
        _codePointList = List.tl(codePointList$1);
        continue ;
      }
      
    } else {
      return true;
    }
  };
}

exports.context = context;
/* No side effect */
