// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var PrecisBidi$BsPrecis = require("./PrecisBidi.bs.js");
var PrecisUnorm$BsPrecis = require("./PrecisUnorm.bs.js");
var PrecisUtils$BsPrecis = require("./PrecisUtils.bs.js");
var PrecisClasses$BsPrecis = require("./PrecisClasses.bs.js");
var PrecisMapping$BsPrecis = require("./PrecisMapping.bs.js");

function bidi(codePointList) {
  var directionList = List.map(PrecisBidi$BsPrecis.getDirectionProperty, codePointList);
  var match = List.mem(/* R */4, directionList) || List.mem(/* AL */5, directionList) || List.mem(/* AN */1, directionList);
  if (match) {
    return PrecisBidi$BsPrecis.validate(codePointList);
  } else {
    return true;
  }
}

function usernameCaseMapped(codePointList) {
  var str = PrecisUnorm$BsPrecis.nfc(PrecisMapping$BsPrecis.toLower(PrecisMapping$BsPrecis.mapWidth(codePointList)));
  var match = bidi(str);
  if (match) {
    var exit = 0;
    var x;
    try {
      x = PrecisClasses$BsPrecis.identifierEnforce(str);
      exit = 1;
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn[0] === PrecisUtils$BsPrecis.PrecisError) {
        var match$1 = exn[1];
        if (match$1 !== 1) {
          if (match$1 !== 0) {
            throw exn;
          }
          throw [
                PrecisUtils$BsPrecis.PrecisError,
                /* Disallowed */0
              ];
        } else {
          throw [
                PrecisUtils$BsPrecis.PrecisError,
                /* Unassigned */1
              ];
        }
      } else {
        throw exn;
      }
    }
    if (exit === 1) {
      return PrecisUtils$BsPrecis.nonEmptyExn(x);
    }
    
  } else {
    throw [
          PrecisUtils$BsPrecis.PrecisError,
          /* BidiError */3
        ];
  }
}

function usernameCasePreserved(codePointList) {
  var str = PrecisUnorm$BsPrecis.nfc(PrecisMapping$BsPrecis.mapWidth(codePointList));
  var match = bidi(str);
  if (match) {
    var exit = 0;
    var x;
    try {
      x = PrecisClasses$BsPrecis.identifierEnforce(str);
      exit = 1;
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn[0] === PrecisUtils$BsPrecis.PrecisError) {
        var match$1 = exn[1];
        if (match$1 !== 1) {
          if (match$1 !== 0) {
            throw exn;
          }
          throw [
                PrecisUtils$BsPrecis.PrecisError,
                /* Disallowed */0
              ];
        } else {
          throw [
                PrecisUtils$BsPrecis.PrecisError,
                /* Unassigned */1
              ];
        }
      } else {
        throw exn;
      }
    }
    if (exit === 1) {
      return PrecisUtils$BsPrecis.nonEmptyExn(x);
    }
    
  } else {
    throw [
          PrecisUtils$BsPrecis.PrecisError,
          /* BidiError */3
        ];
  }
}

function opaqueString(codePointList) {
  var str = PrecisUnorm$BsPrecis.nfc(PrecisMapping$BsPrecis.spaceMap(codePointList));
  var exit = 0;
  var x;
  try {
    x = PrecisClasses$BsPrecis.freeformEnforce(str);
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === PrecisUtils$BsPrecis.PrecisError) {
      var match = exn[1];
      if (match !== 1) {
        if (match !== 0) {
          throw exn;
        }
        throw [
              PrecisUtils$BsPrecis.PrecisError,
              /* Disallowed */0
            ];
      } else {
        throw [
              PrecisUtils$BsPrecis.PrecisError,
              /* Unassigned */1
            ];
      }
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return PrecisUtils$BsPrecis.nonEmptyExn(x);
  }
  
}

function nickname(codePointList) {
  var str = PrecisUnorm$BsPrecis.nfkc(PrecisMapping$BsPrecis.toLower(PrecisMapping$BsPrecis.stripSpaces(PrecisMapping$BsPrecis.spaceMap(codePointList))));
  var exit = 0;
  var x;
  try {
    x = PrecisClasses$BsPrecis.freeformEnforce(str);
    exit = 1;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === PrecisUtils$BsPrecis.PrecisError) {
      var match = exn[1];
      if (match !== 1) {
        if (match !== 0) {
          throw exn;
        }
        throw [
              PrecisUtils$BsPrecis.PrecisError,
              /* Disallowed */0
            ];
      } else {
        throw [
              PrecisUtils$BsPrecis.PrecisError,
              /* Unassigned */1
            ];
      }
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return PrecisUtils$BsPrecis.nonEmptyExn(x);
  }
  
}

function usernameCaseMapped$1(s) {
  return PrecisUtils$BsPrecis.fromCodePointList(usernameCaseMapped(PrecisUtils$BsPrecis.toCodePointList(s)));
}

function usernameCasePreserved$1(s) {
  return PrecisUtils$BsPrecis.fromCodePointList(usernameCasePreserved(PrecisUtils$BsPrecis.toCodePointList(s)));
}

function opaqueString$1(s) {
  return PrecisUtils$BsPrecis.fromCodePointList(opaqueString(PrecisUtils$BsPrecis.toCodePointList(s)));
}

function nickname$1(s) {
  return PrecisUtils$BsPrecis.fromCodePointList(nickname(nickname(PrecisUtils$BsPrecis.toCodePointList(s))));
}

exports.bidi = bidi;
exports.usernameCaseMapped = usernameCaseMapped$1;
exports.usernameCasePreserved = usernameCasePreserved$1;
exports.opaqueString = opaqueString$1;
exports.nickname = nickname$1;
/* PrecisUnorm-BsPrecis Not a pure module */
