// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var PrecisProfiles$BsPrecis = require("../../src/PrecisProfiles.bs.js");

function ucpJuliet(param) {
  var str = "Juliet";
  return Jest.Expect[/* toBe */2](str, Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.usernameCasePreserved(str)));
}

function ucmJuliet(param) {
  return Jest.Expect[/* toBe */2]("juliet", Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.usernameCaseMapped("Juliet")));
}

function nickJuliet(param) {
  return Jest.Expect[/* toBe */2]("juliet", Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.nickname(" Juliet")));
}

function ucpJ(param) {
  var str = "J*";
  return Jest.Expect[/* toBe */2](str, Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.usernameCasePreserved(str)));
}

function ucpSpace(param) {
  return Jest.Expect[/* toThrow */18](Jest.Expect[/* expect */0]((function (param) {
                    return PrecisProfiles$BsPrecis.usernameCasePreserved(" J");
                  })));
}

function ucpBidi(param) {
  return Jest.Expect[/* toThrow */18](Jest.Expect[/* expect */0]((function (param) {
                    return PrecisProfiles$BsPrecis.usernameCasePreserved("א*");
                  })));
}

Jest.describe("Codec Test", (function (param) {
        Jest.test("Username Case Preserved: Juliet", ucpJuliet);
        Jest.test("Username Case Mapped: Juliet -> juliet", ucmJuliet);
        Jest.test("Nickname: _Juliet -> juliet", nickJuliet);
        Jest.test("Username Case Preserved: J*", ucpJ);
        Jest.test("Username Case Preserved: _J", ucpSpace);
        return Jest.test("Username Case Preserved: \xd7\x90*", ucpBidi);
      }));

exports.ucpJuliet = ucpJuliet;
exports.ucmJuliet = ucmJuliet;
exports.nickJuliet = nickJuliet;
exports.ucpJ = ucpJ;
exports.ucpSpace = ucpSpace;
exports.ucpBidi = ucpBidi;
/*  Not a pure module */
