// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var PrecisProfiles$BsPrecis = require("../../src/PrecisProfiles.bs.js");

var codecTests = /* :: */[
  /* tuple */[
    "Foo",
    "foo"
  ],
  /* :: */[
    /* tuple */[
      "foo",
      "foo"
    ],
    /* :: */[
      /* tuple */[
        "Foo Bar",
        "foo bar"
      ],
      /* :: */[
        /* tuple */[
          "foo bar",
          "foo bar"
        ],
        /* :: */[
          /* tuple */[
            "ϔ",
            "ϋ"
          ],
          /* :: */[
            /* tuple */[
              "∞",
              "∞"
            ],
            /* :: */[
              /* tuple */[
                "Richard Ⅳ",
                "richard iv"
              ],
              /* :: */[
                /* tuple */[
                  "       j      ",
                  "j"
                ],
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

function testSingle(input, output) {
  return Jest.Expect[/* toBe */2](output, Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.nickname(input)));
}

function testBuilder(param) {
  var output = param[1];
  var input = param[0];
  return Jest.test("Nickname Test: " + input, (function (param) {
                return testSingle(input, output);
              }));
}

Jest.describe("Nickname Codec Tests", (function (param) {
        return Belt_List.forEach(codecTests, testBuilder);
      }));

exports.codecTests = codecTests;
exports.testSingle = testSingle;
exports.testBuilder = testBuilder;
/*  Not a pure module */
