// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var PrecisProfiles$BsPrecis = require("../../src/PrecisProfiles.bs.js");

var opaquesTest = /* :: */[
  "correct horse battery staple",
  /* :: */[
    "Correct Horse Battery Staple",
    /* :: */[
      "πßå",
      /* :: */[
        "Jack of ♦s",
        /* :: */[
          "foo bar",
          /* [] */0
        ]
      ]
    ]
  ]
];

var opaquesThrow = /* :: */[
  "my cat is a &#x9;by",
  /* :: */[
    "",
    /* [] */0
  ]
];

function testSingleOpaque(input) {
  return Jest.Expect[/* toBe */2](input, Jest.Expect[/* expect */0](PrecisProfiles$BsPrecis.opaqueString(input)));
}

function throwSingleOpaque(input) {
  return Jest.Expect[/* toThrow */18](Jest.Expect[/* expect */0]((function (param) {
                    return PrecisProfiles$BsPrecis.opaqueString(input);
                  })));
}

function testBuilder(input) {
  return Jest.test("Opaque String: " + input, (function (param) {
                return testSingleOpaque(input);
              }));
}

function throwBuilder(input) {
  return Jest.test("Opaque Throw: " + input, (function (param) {
                return throwSingleOpaque(input);
              }));
}

Jest.describe("Opaque String Codec Tests", (function (param) {
        Belt_List.forEach(opaquesTest, testBuilder);
        return Belt_List.forEach(opaquesThrow, throwBuilder);
      }));

exports.opaquesTest = opaquesTest;
exports.opaquesThrow = opaquesThrow;
exports.testSingleOpaque = testSingleOpaque;
exports.throwSingleOpaque = throwSingleOpaque;
exports.testBuilder = testBuilder;
exports.throwBuilder = throwBuilder;
/*  Not a pure module */
