// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var PrecisUnorm$BsPrecis = require("../../src/PrecisUnorm.bs.js");

function encodingTest1(param) {
  return Jest.Expect[/* toEqual */12](PrecisUnorm$BsPrecis.nfcString("¡™£¢∞§¶•ªº–≠œ∑´®†¥¨ˆøπ““‘«åß∂ƒ©˙∆˚¬…æ≈ç√∫˜µ≤≥÷⁄€‹›ﬁﬂ‡°·‚—±Œ„´‰ˇÁØ∏”’»/* ÍÎ˝ÓÔÒÚÆ¸˛Ç◊˜Â¯˘¿1234567890-=qwertyuiop[]\\asdfghjkl;\'zxcvbnm,./"), Jest.Expect[/* expect */0]("¡™£¢∞§¶•ªº–≠œ∑´®†¥¨ˆøπ““‘«åß∂ƒ©˙∆˚¬…æ≈ç√∫˜µ≤≥÷⁄€‹›ﬁﬂ‡°·‚—±Œ„´‰ˇÁØ∏”’»/* ÍÎ˝ÓÔÒÚÆ¸˛Ç◊˜Â¯˘¿1234567890-=qwertyuiop[]\\asdfghjkl;\'zxcvbnm,./"));
}

Jest.describe("NFC Encoding Tests ", (function (param) {
        return Jest.test("NFC Test 1", encodingTest1);
      }));

exports.encodingTest1 = encodingTest1;
/*  Not a pure module */
